name: "e_stat"
version: "1.0.0"

profile: "e_stat"

model-paths: ["models"]
macro-paths: ["macros", "shared/macros"]
clean-targets: ["target", "dbt_packages"]

seeds:
  e_stat:
    +database: e_stat
    +schema: main

models:
  e_stat:
    +database: e_stat
    +materialized: view
    boundary:
      raw:
        +materialized: table
      stg:
        +materialized: table
    census:
      raw:
        +materialized: table
      stg:
        +materialized: table
    code:
      raw:
        +materialized: table
      stg:
        +materialized: table
    economic_census:
      raw:
        +materialized: table
      stg:
        +materialized: table
    local_finance:
      raw:
        +materialized: table
      stg:
        +materialized: table
    manufacture:
      raw:
        +materialized: table
      stg:
        +materialized: table
    migration:
      raw:
        +materialized: table
      stg:
        +materialized: table
    resident_registry:
      raw:
        +materialized: table
      stg:
        +materialized: table
    retail_price:
      raw:
        +materialized: table
      stg:
        +materialized: table
    welfare_facility:
      raw:
        +materialized: table
      stg:
        +materialized: table
